# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - blessedsidecar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Python, create venv, and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r ./router-app/requirements.txt
      
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Zip artifact for deployment
        run: |
          cd router-app
          zip -r ../release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
      
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: sitecontainerssampleacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A0CC9BC301454048B276D44640F4817D }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_D5DF9FCBBA0B44269C84675BD466AD75 }}

      - name: Build and push container hello-app image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./hello-app
          push: true
          tags: sitecontainerssampleacr.azurecr.io/sitecontainerssampleacr/test/hello-app:${{ github.sha }}
          file: ./hello-app/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5346AF9256E449EB96218509E03DBA01 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_98661BEA81BB42DBA5446F0C1377425E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F17024D5551C4BAD9A075B1DBB57726C }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@sidecar-testing-from-v3
        id: deploy-to-webapp
        with:
          app-name: 'blessedsidecar'
          slot-name: 'Production'
          blessed-app-sitecontainers: true
          sitecontainers-config: >-
            [
              {
                "name": "hello-app",
                "image": "sitecontainerssampleacr.azurecr.io/sitecontainerssampleacr/test/hello-app:${{ github.sha }}",
                "targetPort": 5001,
                "isMain": false,
                "volumeMounts": [{"containerMountPath": "abc", "data" : "def", "readOnly" : true, "volumeSubPath": "xyz"}],
                "environmentVariables": [{"name": "testing", "value": "TestEnv"}]
              }
            ]
          
